project/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('view-projects', views.ProjectList.as_view()),
    path('add-project/', views.CreateProject.as_view()),
    path('edit-project/<slug>', views.UpdateProject.as_view()),
    path('delete-project/<slug>', views.DeleteProject.as_view()),
    path('view-tasks', views.TaskList.as_view()),
    path('add-task/', views.CreateTask.as_view()),
    path('edit-task/<slug>', views.UpdateTask.as_view()),
    path('delete-task/<slug>', views.DeleteTask.as_view()),
]

project_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('project.urls', 'project'), namespace='project')),
    path('api/v1/', include('project.api_urls')),
]

project/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class CommonColumnModel(models.Model):
    slug = models.SlugField(max_length=200, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Project(CommonColumnModel):

    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    assigned_users = models.ManyToManyField(User, related_name='project_assigned')
    deadline = models.DateField()
    status = models.BooleanField(default=True)

    class Meta:
        ordering = ['name']
        db_table = 'project'

    def __str__(self):
        return self.name


class Task(CommonColumnModel):
    CREATED = 'created'
    IN_PROGRESS = 'in_progress'
    TO_VERIFY = 'to_verify'
    READY_TO_RELEASE = 'ready_to_release'
    RELEASED = 'released'

    STATUS = (
        (CREATED, 'CREATED'),
        (IN_PROGRESS, 'IN PROGRESS'),
        (TO_VERIFY, 'TO VERIFY'),
        (READY_TO_RELEASE, 'READY TO RELEASE'),
        (RELEASED, 'RELEASED'),
    )

    project = models.ForeignKey(Project, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=80)
    description = models.TextField(null=True, blank=True)
    assigned_users = models.ManyToManyField(User, related_name='task_assigned')
    status = models.CharField(max_length=20, choices=STATUS, default=CREATED)

    class Meta:
        db_table = 'task'
        ordering = ['project', 'name']

    def __str__(self):
        return self.name

project/forms.py
from datetime import date

from django import forms
from django.core.exceptions import ValidationError
from django.utils.text import slugify
from .models import Task
from .models import Project
from django.contrib.auth.models import User


def no_past_date(value):
    today = date.today()
    if value < today:
        raise ValidationError('Deadline Date cannot be a past date.')


class ProjectRegisterForm(forms.ModelForm):
    deadline = forms.DateField(help_text='Format dd-mm-yyyy', input_formats=['%d-%m-%Y', '%Y-%m-%d'], validators=[no_past_date])

    class Meta:
        model = Project
        exclude = ('slug', 'created', 'updated')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    def save(self, commit=True):
        project = super().save(commit=False)
        project.slug = slugify(str(self.cleaned_data['name']))
        project.save()
        self.save_m2m()
        return project


class TaskRegisterForm(forms.ModelForm):

    class Meta:
        model = Task
        exclude = ('slug', 'created', 'updated')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    def save(self, commit=True):
        project = super().save(commit=False)
        project.slug = slugify(str(self.cleaned_data['name']))
        project.save()
        self.save_m2m()
        return project

project/views.py
# Create your views here.
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from project.forms import TaskRegisterForm, ProjectRegisterForm
from project.models import Project, Task


class ProjectList(ListView):
    model = Project
    paginate_by = 3
    context_object_name = 'projects'
    template_name = 'project/project-list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class CreateProject(CreateView):
    model = Project
    form_class = ProjectRegisterForm
    context_object_name = 'form'
    template_name = 'project/project-add.html'
    success_url = '/view-projects'


class UpdateProject(UpdateView):
    model = Project
    form_class = ProjectRegisterForm
    context_object_name = 'form'
    template_name = 'project/project-add.html'
    success_url = '/view-projects'


class DeleteProject(DeleteView):
    model = Project
    success_url = '/view-projects'


class TaskList(ListView):
    model = Task
    paginate_by = 100
    context_object_name = 'tasks'
    template_name = 'project/task-list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class CreateTask(CreateView):
    model = Task
    form_class = TaskRegisterForm
    context_object_name = 'form'
    template_name = 'project/task-add.html'
    success_url = '/view-tasks'


class UpdateTask(UpdateView):
    model = Task
    form_class = TaskRegisterForm
    context_object_name = 'form'
    template_name = 'project/task-add.html'
    success_url = '/view-tasks'


class DeleteTask(DeleteView):
    model = Task
    success_url = '/view-tasks'

templates/project/project-add.html
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <title>Add Project</title>
</head>
{% load widget_tweaks %}
{% block content %}
<body>
<div class="container border pt-3 my-3">
  <div class="jumbotron">
    <h1>Add Project</h1>
  </div>
  <form method="post" novalidate >
    {% csrf_token %}
    {% if form.non_field_errors %}
      <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
          {{ error }}
        {% endfor %}
      </div>
    {% endif %}
    {% for field in form.visible_fields %}
      <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
          {% if field.errors %}
            {% render_field field class="form-control is-invalid" %}
            {% for error in field.errors %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% else %}
            {% render_field field class="form-control is-valid" %}
          {% endif %}
        {% else %}
          {% render_field field class="form-control" %}
        {% endif %}

        {% if field.help_text %}
          <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
      </div>
    {% endfor %}

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
</body>
{% endblock %}
</html>

templates/project/project-list.html
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <title>Project List</title>
</head>
<div class="container border pt-3 my-3">
  <div>
    <h3>Project List</h3>
    <div style="float: right;"><a href="/add-project/"> Add/Edit Project</a></div>
  </div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Assigned Users</th>
        <th>Created</th>
        <th>Deadline</th>
      </tr>
    </thead>
    <tbody>
      {% for project in projects %}
        <tr>
          <td>{{ project.name }}</td>
          <td>{{ project.description }}</td>
          <td>{% for name in project.assigned_users.all %}{{ name|title }}, {% endfor %}</td>
          <td>{{ project.created }}</td>
          <td>{{ project.deadline }}</td>
          <td><a href="/edit-project/{{project.slug}}">Edit Project</a> |
              <a href="/add-task/">  Link Tasks</a> |
              <a href="/delete-project/{{project.slug}}">  Delete</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</div>


</html>

templates/project/project_confirm_delete.html
<!DOCTYPE html>
<html lang="en">

<body>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
</body>
</html>

templates/project/task-add.html
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <title>Add Project</title>
</head>
{% load widget_tweaks %}
{% block content %}
<body>
<div class="container border pt-3 my-3">
  <div class="jumbotron">
    <h1>Add/Edit Task</h1>
  </div>
  <form method="post" novalidate >
    {% csrf_token %}
    {% if form.non_field_errors %}
      <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
          {{ error }}
        {% endfor %}
      </div>
    {% endif %}
    {% for field in form.visible_fields %}
      <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
          {% if field.errors %}
            {% render_field field class="form-control is-invalid" %}
            {% for error in field.errors %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% else %}
            {% render_field field class="form-control is-valid" %}
          {% endif %}
        {% else %}
          {% render_field field class="form-control" %}
        {% endif %}

        {% if field.help_text %}
          <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
      </div>
    {% endfor %}

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
</body>
{% endblock %}
</html>

templates/project/task-list.html
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <title>Task List</title>
</head>
<div class="container border pt-3 my-3">
  <div>
    <h3>Task List</h3>
    <div style="float: right;"><a href="/add-task/"> Add/Edit Task</a></div>
  </div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Project</th>
        <th>Name</th>
        <th>Description</th>
        <th>Status</th>
        <th>Assigned Users</th>
        <th>Created</th>
      </tr>
    </thead>
    <tbody>
      {% for task in tasks %}
        <tr>
          <td>{{ task.project }}</td>
          <td>{{ task.name }}</td>
          <td>{{ task.description }}</td>
          <td>{{ task.get_status_display }}</td>
          <td>{% for name in task.assigned_users.all %}{{ name|title }}, {% endfor %}</td>
          <td>{{ task.created }}</td>
          <td><a href="/edit-task/{{task.slug}}">  Edit</a> |
              <a href="/delete-task/{{task.slug}}">  Delete</a>
          </td>

        </tr>
      {% endfor %}
    </tbody>
  </table>

    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</div>


</html>

templates/project/task_confirm_delete.html
<!DOCTYPE html>
<html lang="en">

<body>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
</body>
</html>